# Generated by Django 3.2.25 on 2024-06-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_solicitor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
