# Generated by Django 3.2.25 on 2024-06-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240610_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estates', to='core.application'),
        ),
    ]
