# Generated by Django 3.2.25 on 2024-06-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240611_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='description',
        ),
    ]
