# Generated by Django 3.2.25 on 2024-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20240611_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
