# Generated by Django 3.2.25 on 2024-06-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_estate_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitor',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitors', to='core.agency'),
        ),
    ]
