# Generated by Django 3.2.25 on 2024-06-12 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_solicitor_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_applications_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
